### ISSUE TITLE
Missing characters in extracted body

### ISSUE THREAD

**Issue by lucc** [pazz/alot#1360] opened 2018-12-24 12:47 UTC
For some content transfer encodings and charsets some characters are missing in the extracted body. An example can be seen in the test added in #1359. As that test demonstrates the problem seems to be somewhere below `alot.db.utils.extract_body()`.  We should try to find more relevant combinations of encoding and charset, add tests and ultimatly fix it :)

**Software Versions**
- Python version: 3.7
- Alot version: 0.8-4-g9ff655ba

**Comment by lucc** [comment] 2019-01-06 09:17
It is marked as an expected failure because the bug is known and we did not yet fix it. I created this test after the bug report was issued in order to help us fix it. See the #1359 I mentioned above.

If you want to provide more test cases that is very much appreciated. So if you have any *other* combinations of encoding and charset I am very interested.

**Comment by jljusten** [comment] 2019-02-04 08:37
@lucc: Hey. I think you've been the only one to look into this issue, but I guess it's stalled a bit?

We're holding off on packaging 0.8 for debian due to this issue. We would probably cherry-pick a patch for this back to the 0.8 release if a fix is found.

**Comment by mjg** [comment] 2019-02-04 17:07
The problem bisects back to commit 176cffcd ("refactor alot.db.utils.remove_cte", 2018-12-04) which claims to refactor and make the code more lenient.

In fact, it does one more thing: it changes the fallback for the case of decoding errors to `bp.decode(enc, errors='ignore')` rather than `helper.try_decode(bp)`. Whether this is more lenient or not is a matter of definition; in any case it's the cause of the missing characters. I don't know if this change is intentional and maybe improves other things. The "fix" for me is a one-liner, obviously, but may restore behaviour that this commit wanted to change.  See PR #1375

In general, I'd suggest to refactor in one commit and change behaviour in another one...

**Comment by pazz** [comment] 2019-02-10 20:33
I guess this can be closed then?

**Comment by josch** [comment] 2019-02-10 23:31
Yes, it is fixed by PR #1375.

**Closed** 2019-02-11 08:24 UTC
Labels: bug, important, py3k
