### ISSUE TITLE
Not compatible with notmuch2 0.35 bindings

### ISSUE THREAD

**Issue by inglor** [pazz/alot#1597] opened 2022-02-15 21:10 UTC
Before you submit a bug report, please make sure that the issue still exists on the master branch!

**Describe the bug**
notmuch 0.35 released a few days ago and the test suite fails due to breaking changes on the `_database.py`. I think the commit which introduce these changes is https://github.com/notmuch/notmuch/commit/8b737af28bc377db3e661a5744f3b7479b7ce485

**Software Versions**
- Python version: 3.10
- Notmuch version: 0.35
- Alot version: 0.10, master

**To Reproduce**
Steps to reproduce the behaviour:
1. execute test suite with notmuch2 bindings 0.35

**Error Log**
Test suite error:
```
ERROR: test_save_named_query (tests.db.test_manager.TestDBManager)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/build/alot/src/alot-0.10/alot/db/manager.py", line 92, in flush
    db = Database(path=self.path, mode=mode)
  File "/usr/lib/python3.10/site-packages/notmuch2/_database.py", line 160, in __init__
    raise errors.NotmuchError(ret, msg)
notmuch2.NoConfigError: Error: cannot load config file.


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/build/alot/src/alot-0.10/tests/db/test_manager.py", line 49, in test_save_named_query
    self.manager.flush()
  File "/build/alot/src/alot-0.10/alot/db/manager.py", line 175, in flush
    raise e
  File "/build/alot/src/alot-0.10/alot/db/manager.py", line 94, in flush
    raise DatabaseLockedError()
alot.db.errors.DatabaseLockedError
```

**Comment by oliversturm** [comment] 2022-06-27 21:37
On Arch Linux I have seen this problem for a long time, and worked around it by downgrading to notmuch 0.34. I didn't run test suites though - I simply can't use alot because it comes up with a blank screen at all times. Now I'm running on a Mac where alot and notmuch are installed via brew (see versions below), and it's not trivial to downgrade.

For clarity and completeness, here are steps I take:

1. Run `alot -n <mynotmuchconfig> -l ./alot.log`
2. The screen goes completely blank. I can use `o` to search, `d` to leave the (invisible) result screen, `q` to quit alot, but I must do it all blind.
3. I find this output at the top of the log file:

```
INFO:ui:setup gui in 256 colours
ERROR:ui:Traceback (most recent call last):
  File "/opt/homebrew/Cellar/alot/0.10/libexec/lib/python3.9/site-packages/alot/buffers/search.py", line 63, in rebuild
    self.result_count = self.dbman.count_messages(self.querystring)
  File "/opt/homebrew/Cellar/alot/0.10/libexec/lib/python3.9/site-packages/alot/db/manager.py", line 254, in count_messages
    db = Database(path=self.path, mode=Database.MODE.READ_ONLY)
  File "/opt/homebrew/opt/notmuch/libexec/lib/python3.9/site-packages/notmuch2/_database.py", line 160, in __init__
    raise errors.NotmuchError(ret, msg)
notmuch2.NoConfigError: Error: cannot load config file.

... nested exception details
```

Versions on the Mac:

```
➜ python3 --version
Python 3.9.13

➜ alot --version
0.10

➜ notmuch --version
notmuch 0.36
```

**Comment by oliversturm** [comment] 2022-06-27 22:07
FWIW, I went through the steps to downgrade notmuch and alot as far as required to make things work - perhaps this will be useful to someone who uses brew to install the two.

```bash
# find the commit id you want
> brew log notmuch

# insert commit id in the URL - this is notmuch 0.34.3
> wget https://raw.githubusercontent.com/Homebrew/homebrew-core/356895dfc9b9f9ce2e0f532868253ec7b3830efd/Formula/notmuch.rb

> brew uninstall --ignore-dependencies notmuch
> brew install ./notmuch.rb
> brew pin notmuch

# same job for alot
> brew log alot

# commit id for alot 0.9.1_2 here
> wget https://raw.githubusercontent.com/Homebrew/homebrew-core/8748606303fdafe1125e75fa0b95401ee3040dd4/Formula/alot.rb

> brew uninstall alot
> brew install --ignore-dependencies ./alot.rb
> brew pin alot
```

This combination of notmuch 0.34.3 and alot 0.9.1 works correctly on this Mac. I tried to downgrade only notmuch and leave alot alone, but that didn't help - a bit surprising because I think I was using 0.34 and 0.10 together on Linux (but I'd have to double-check in case that's important to anyone).

**Comment by jaquer** [comment] 2023-07-18 16:50
I also ran into this issue, and was able to work around it by setting an environment variable to the location of the config file like so:

`NOTMUCH_CONFIG=<path to custom config> alot`

NixOS, alot 0.10, notmuch 0.37

**Comment by pazz** [comment] 2023-07-19 07:44
Thanks for this discussion.

For what It's worth, I cannot reproduce this on Debian.
I am running notmuch 0.37 and alot 0.10 both from their respective git
main branches.

P


Quoting Arturo R. (2023-07-18 17:51:07)

**Comment by GuillaumeSeren** [comment] 2024-03-15 17:10
Hello there,
we're having this issue on gentoo as well (https://bugs.gentoo.org/874372).
I am pretty sure the test went fine when I pushed this new release.

**Comment by pazz** [comment] 2024-08-06 14:05
Sorry for the long silence. It may be that the path to the notmuch index is not set up correctly.
Coud someone please add a logging command [to db/DBManager](https://github.com/pazz/alot/blob/master/alot/db/manager.py#L87)

```python
       logging.debug("DB index path: %s" self.path))
```
and report back?

**Comment by pazz** [comment] 2024-08-06 14:26
> I also ran into this issue, and was able to work around it by setting an environment variable to the location of the config file like so:
> 
> `NOTMUCH_CONFIG=<path to custom config> alot`
> 
> NixOS, alot 0.10, notmuch 0.37

This indeed goes to the heart of the matter it seems.

Alot opens notmuchs database via `notmuch2.Database(..)` without the path to the notmuch config.
According to the sources of these bindings, this then defaults to "SEARCH" (`NULL` in the c context, meaning let notmuch figure it out).
Then according to man (1) notmuch:

```
If config_path is NULL use the path specified  
in environment variable NOTMUCH_CONFIG, if non-empty
by XDG_CONFIG_HOME/notmuch/ where XDG_CONFIG_HOME defaults to '$HOME/.config'.
by $HOME/.notmuch-config

If config_path is '' (empty string) then do not open any configuration file.
profile Name of profile (configuration/database variant).  
If non-NULL, append to the directory / file path determined for config_path and database_path.  
If NULL then use  
environment variable NOTMUCH_PROFILE if defined,
otherwise 'default' for directories and '' (empty string) for paths.
database Pointer to database object. May not be NULL.
```

One way to fix this issue for alot is simply to always open notmuch2.Database with an explicit `config=''` parameter, causing it to completely ignore the users notmuch config (except for where we read it ourselves directly).
Possibly this is not the desired behaviour, because some users may want to use saved searches defined in notmuch's config, which may be affected.

thoughts?

**Comment by oliversturm** [comment] 2024-08-06 15:17
On macOS here -- I don't have any `XDG_CONFIG_HOME`.

Also, not sure how relevant this is, but I always run alot with `--notmuch-config <somefile>` because I have multiple config files. I don't remember ever running without this, but I always use the option syntax, not the environment variable.

**Comment by pazz** [comment] 2024-08-07 07:52
> On macOS here -- I don't have any `XDG_CONFIG_HOME`.
> 
> Also, not sure how relevant this is, but I always run alot with `--notmuch-config <somefile>` because I have multiple config files. I don't remember ever running without this, but I always use the option syntax, not the environment variable.

OK right, this explains the issue with the empty screen for your case: that config option is used only when alot itself is reading off the notmuch config, not for opening the notmuch database. That call will internally start looking for the notmuch config at standard places, ultimately ~/.config/notmuch or similar, and fail if the file does not exist.

The fix I suggest above would work in your case I suppose. Perhaps a better alternative really would be to pass on the path to the notmuch config given as alot cli argument.

**Comment by oliversturm** [comment] 2024-08-07 08:42
> ... fail if the file does not exist.

I guess things could be improved a lot by failing in a meaningful way, i.e. rendering a *useful* error message right on the console. 

In [my post above](https://github.com/pazz/alot/issues/1597#issuecomment-1167933322), the error message (in a log that I needed to activate first!) is this:

```
notmuch2.NoConfigError: Error: cannot load config file.
```

I guess I don't understand exactly what you said about alot and notmuch both reading the config file -- this message seems to originate from notmuch, while I thought you just said the error occurred during alot's access attempt? Well, anyway... it's pointless the way it is, but if it included the actual path of the file where access is attempted, then I would have noticed right away that it wasn't a valid path.

The way it is, all I thought was "well, I've got a config file that worked recently, I'm passing it the same way I always did, if you have a problem with that you're not explaining it very well".

Just trying to learn something from this...

> Perhaps a better alternative really would be to pass on the path to the notmuch config given as alot cli argument.

I would expect nothing less when using a cli argument called `--notmuch-config` :-)

**Comment by oliversturm** [comment] 2024-08-07 08:51
Offtopic -- @pazz the [ha-index](https://www.liafa.univ-paris-diderot.fr/~haberm/haindex.html) linked from your homepage is excellent. Thanks for that laugh!

**Comment by pazz** [comment] 2024-08-07 11:09
@oliversturm could you try the suggested fix? (thx)

**Comment by oliversturm** [comment] 2024-08-07 11:23
> @oliversturm could you try the suggested fix? (thx)

I'm sorry, I'm not clear what fix you refer to. This?

> One way to fix this issue for alot is simply to always open notmuch2.Database with an explicit config='' parameter, causing it to completely ignore the users notmuch config (except for where we read it ourselves directly).

If so, I took this to mean something you considered changing in code (since `notmuch2.Database` refers to an API call, right?). In case that's not what you mean, where and how do I apply a `config=''` parameter as you suggest?

If you can clarify your suggestion, I will test it --  I'm a bit hesitant to unravel the "pinned" brew installation that works for me right now, but if it helps fix this issue it'll be worth it.

**Comment by pazz** [comment] 2024-08-07 12:01
sorry, I meant checking out [the notmuch-config branch linked above](https://github.com/pazz/alot/tree/notmuch-config) and run alot from there.

**Comment by oliversturm** [comment] 2024-08-07 15:30
Right! Sorry about that... yes, I tried it and it works on the Mac now, with notmuch version 0.38.3 pulled in by brew. 
(I actually applied the diff of your branch right to the alot version brew pulled down, instead of building from scratch.)

**Comment by pazz** [comment] 2024-08-12 10:05
I've just merged the fix into the master branch. Thanks again for reporting the issue!

**Closed by pazz** 2024-08-12 10:05 UTC
Labels: bug, backend
