### ISSUE TITLE
mailcap module will be removed in 3.13

### ISSUE THREAD

**Issue by jelly** [pazz/alot#1649] opened 2024-04-17 19:33 UTC
**Describe the bug**

While [Python 3.13](https://docs.python.org/3.13/whatsnew/3.13.html#summary-release-highlights) has not been released yet, it's release will remove the `mailcap` module. 

With as note:
> mailcap. The [mimetypes](https://docs.python.org/3.13/library/mimetypes.html#module-mimetypes) module provides an alternative. (Contributed by Victor Stinner in [gh-104773](https://github.com/python/cpython/issues/104773).)

**Software Versions**
- Python version: 3.13
- Alot version: master

**Comment by lucc** [comment] 2024-04-17 19:41
Duplicate of #1632

**Closed by lucc** 2024-04-17 19:41 UTC

**Comment by jelly** [comment] 2024-04-17 21:40
Sorry, missed that one when searching.
