### ISSUE TITLE
Trailing comma when group replying

### ISSUE THREAD

**Issue by josch** [pazz/alot#874] opened 2016-07-01 08:49 UTC
Hi,

I'm running alot from git. When I group reply to an email with the following headers:

```
From: Santiago Vila <sanvila@unex.es>
To: Johannes Schauer <josch@debian.org>
cc: 825359@bugs.debian.org, deller@gmx.de
```

Then the following email will be generated:

```
Cc: 825359@bugs.debian.org, deller@gmx.de
To: Santiago Vila <sanvila@unex.es>,
From: Johannes Schauer <josch@debian.org>
```

Notice the trailing comma in the produced `To` header. The email I initially mentioned is publically archived here (this is also why I did not obfuscate the headers): https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=825359#29 By clicking the mbox link you can download the full email to see this effect yourself.

The trailing comma confuses some email clients (alpine). It is not necessary and should not be generated.

**Comment by pazz** [comment] 2016-07-01 08:55
I agree that comma shouldn't be there.
To find out where the error is introduced,
It'd help to add some debug logs to alot/commands/thread.py,
around line 231, to check the content of the `recipients` variable..

Quoting josch (2016-07-01 09:49:14)

**Comment by josch** [comment] 2016-07-01 09:18
Awesome! Thanks to your help, I got it now. The following code block:

```python
                # append To addresses if not replying to self sent message
                if sender_address not in my_addresses:
                    cleared = self.clear_my_address(
                        my_addresses, mail.get_all('To', []))
                    recipients.append(cleared)
```

wil append an empty string if `clear_my_address()` returns one. The problem would elegantly be solved if `clear_my_address()` would not return a string of already concatenated addresses but a list of addresses. Then one could just do a `recipients.extend(cleared)` and the problem would be fixed.

Incidentally, this is exactly what I proposed in issue #818 and thus the patch I proposed in #818 would also automatically fix this bug.

**Comment by pazz** [comment] 2016-07-04 16:07
Quoting josch (2016-07-01 10:18:10)
>    Incidentally, this is exactly what I proposed in issue [1]#818 and thus
>    the patch I proposed in [2]#818 would also automatically fix this bug.


Thanks. I will happily push these changes if you send a PR.
IIRC, #818 was loosely dependent on #823, which was solved (by you) but not
pushed yet :)

**Comment by josch** [comment] 2016-07-04 16:43
Thanks, unfortunately I have very little time and while creating these pull requests is somewhere on my TODO list, there is lots of other stuff ahead of it. So I'd be very happy if someone could take the diffs I presented in the bugs I reported and make them into proper commits with helpful commit messages, add code comments, test them thoroughly and then push them to github. I also don't care about any attribution, so whoever does the "boring" work to do things properly may freely attach their name to the commit.

**Comment by pazz** [comment] 2017-01-23 19:42
with #818 merged I believe this is settles as well?

**Comment by josch** [comment] 2017-01-23 20:49
Nearly. I now get:


    ERROR:ui:Traceback (most recent call last):
      File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 319, in addCallback
        callbackKeywords=kw)
      File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 308, in addCallbacks
        self._runCallbacks()
      File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 651, in _runCallbacks
        current.result = callback(current.result, *args, **kw)
      File "alot/ui.py", line 670, in call_apply
        return defer.maybeDeferred(cmd.apply, self)
    --- <exception caught here> ---
      File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 150, in maybeDeferred
        result = f(*args, **kw)
      File "alot/commands/thread.py", line 276, in apply
        if any(addr in lists for n, addr in getaddresses(allrecipients)):
      File "/usr/lib/python2.7/email/utils.py", line 106, in getaddresses
        all = COMMASPACE.join(fieldvalues)
    exceptions.TypeError: sequence item 1: expected string, list found


This is the fix:


```diff
--- a/alot/commands/thread.py
+++ b/alot/commands/thread.py
@@ -195,7 +195,7 @@ class ReplyCommand(Command):
         sender = mail['Reply-To'] or mail['From']
         my_addresses = settings.get_addresses()
         sender_address = parseaddr(sender)[1]
-        cc = ''
+        cc = []
 
         # check if reply is to self sent message
         if sender_address in my_addresses:
@@ -269,7 +269,7 @@ class ReplyCommand(Command):
         # set Mail-Followup-To header so that duplicates are avoided
         if settings.get('followup_to'):
             # to and cc are already cleared of our own address
-            allrecipients = [to] + [cc]
+            allrecipients = [to] + cc
             lists = settings.get('mailinglists')
             # check if any recipient address matches a known mailing list
             if any(addr in lists for n, addr in getaddresses(allrecipients)):
```

**Comment by pazz** [comment] 2017-01-23 21:12
wait what? I just relayed your patch from #818 .. was that one incorrect or did i miss something?
how do you produce the above error?

**Comment by josch** [comment] 2017-01-23 21:24
The patch in #818 was either incorrect or I didn't test properly or something else changed in the meantime. The problem comes from the piece of code that handles mailing lists. So I guess you could reproduce it by group replying to an email that alot knows comes from a mailing list.

**Comment by pazz** [comment] 2017-01-25 11:15
can you please confirm that this issue is still there? #997 (now merged) touched the relevant code.

**Comment by josch** [comment] 2017-01-25 11:26
Yes, the problem `expected string, list found` still persists in the master branch.

**Comment by pazz** [comment] 2017-01-25 11:27
thanks

**Comment by lucc** [comment] 2017-01-25 12:01
How can we reproduce the new failure on the current master (218c0f449924b6e0daeb241ca3eade4c5bf4932c)? I downloaded the mail you mentioned (with id alpine.DEB.2.11.1607010200040.22146@tulipan.isla-invisible.es) and tried `:reply`, `:reply --all`, `:reply --list=true`, `:reply --list=false` but I don't get any exceptions.

**Comment by josch** [comment] 2017-01-25 12:04
You need to have in your config:
```
honor_followup_to = True
followup_to = True
```

**Comment by lucc** [comment] 2017-01-25 14:14
@josch can you check #1003?

**Comment by josch** [comment] 2017-01-25 14:21
#1003 seems to add exactly the patch I proposed above. Why would you like me to check again?

**Comment by lucc** [comment] 2017-01-25 14:27
Ok, sorry I thought you could have a look because I hope to close this issue for 0.5.  But it is as you said, so I assume this is fixed :)

**Closed by lucc** 2017-01-25 14:27 UTC
Labels: bug
