### ISSUE TITLE
Duscussion: release strategy

### ISSUE THREAD

**Issue by lucc** [pazz/alot#972] opened 2017-01-14 12:15 UTC
## Questions 

1. Do we want a special release strategy? That would mean that we have some "defined" way to decide what goes into a minor release (like 0.5) and what goes into a patch release (like 0.4.1).
2. We have two open [milestones](https://github.com/pazz/alot/milestones) here on github, one for [0.4]( https://github.com/pazz/alot/milestone/5) which still has unfinished items although [0.4 is released](https://github.com/pazz/alot/releases/tag/0.4). Do we move this stuff to the [0.5 milestone](https://github.com/pazz/alot/milestone/8)?
3. Is it justified to push out 0.4.1 soonish as there are already many patches that have accumulated on master and some might fix bugs that people are interested in?
4. Should we use [semantic versioning](http://semver.org)?
5. Are there issues with packaging downstream depending on what we do?

## My answers

1. Not really "defined" but it would be nice to use the milestones more and also prepare 0.4.1.  I do think it is always ok to move stuff between milestones and to release something.  Also we are not forced to release if the github milestone is "done".
2. yes see 1. I think it reduces confusion.
3. yes
4. yes. We are still pre 1.0 so there are no major releases yet, that leaves us pretty "free" atm. And semver is a good thing in general as far as I understand it. (I think of it like a well defined API for version numbers, and well defined APIs are always good.)
5. ?

**Comment by dcbaker** [comment] 2017-01-14 22:10
I am very much in favor of using sematic versioning, so only make .z releases for bug fixes.

One thing that I would suggest doing (other projects I've worked on do this), is brach for releases. So when we're ready to cut 0.5, we'll make a 0.5 branch, and then we can test that and push bug fixes into it as we need to, and make releases out of that. That allows us to keep adding features to master without worry about breaking the releases.

**Comment by lucc** [comment] 2017-01-15 12:41
Branching model: something like a reduced form of [git flow](http://nvie.com/posts/a-successful-git-branching-model/). The simplest reduction would be
* `master` for general development
* at some point we branch `release/x.y.z` from `master` and do not add new features but only fixes to that (`master` also has to get all of these commits while it can also get more)

I am ok with having a kind of feature freeze for a release at some point and prepare the release in a separate branch. I suggest we try this with some of the next releases and get a feeling on when and how we do it.

**Comment by pazz** [comment] 2017-01-15 20:34
1,2: I'm OK with using github milestones for this.
3: sure, why not.
4: maybe. There is also [PEP440](https://www.python.org/dev/peps/pep-0440/#version-scheme) which we (kind of) use, regarding the "dev" suffix..
5: I don't think packagers will be affected much by what we decide for our versioning scheme unless we begin to release versions in some sense smaller than the current version string.

release branches: Sure, good idea. since master is now what used to be "testing" (now retired) for a long while, i think this makes sense.

**Comment by pazz** [comment] 2017-01-17 16:03
I have removed the 0.4 milestone as it mostly contained minor feature requests and some things that require a rewrite of the MIME parser, which is a bigger issue. None of these issues I consider important enough to justify immediate actions.

As far as I understand, the PEP440 defined "dev" suffixes in inter-release version strings do not really clash with the release strings.

I've just browsed through the commit history since 0.4 and it is indeed mostly cleanups, so I'm all for releasing 0.4.1 soon.
There seems to be a consensus that 0.5 should be about adding unit tests. Anything else that you guys want to see go in there?
Another matter is about the major version number. I think it is fair to say that alot is sufficiently mature (rather old) to justify a bump to version 1.0. The configs will probably not change much anymore,
but such a bump will basically amount to a commitment on our part to guarantee that the config format is stable. Opinions?

**Comment by dcbaker** [comment] 2017-01-17 17:59
If we want to update to python 3 only I would say that would be a pretty major break in functionality, enough to consider a major version bump (it's a non-backwards compatible change). If we're thinking about a hybrid code base then I'm not as concerned.

**Comment by lucc** [comment] 2017-01-17 20:32
Is there any reason for a end user application to support both python versions? For a library there certainly is. So my current feeling is to drop py2 some time (soon?) after we implement py3. And this in turn makes me go with @dcbaker to wait with 1.0 until we have py3.

**Comment by pazz** [comment] 2017-01-17 20:36
Quoting Lucas Hoffmann (2017-01-17 20:32:28)
>    Is there any reason for a end user application to support both python
>    versions? For a library there certainly is. So my current feeling is to
>    drop py2 some time (soon?) after we implement py3. And this in turn makes
>    me go with [1]@dcbaker to wait with 1.0 until we have py3.

OK, let's do it like that.

**Comment by dcbaker** [comment] 2017-01-18 00:12
I've put together a mock up of a 0.4-stable branch [here](https://github.com/dcbaker/alot/tree/wip/0.4-stable). I've pulled in what I *think* are all of the relevant bug fixes (not feature work or refactors) that have landed since 0.4. Does that look like a reasonable 0.4.1 release? Obviously once there's a stable branch on pazz's copy we'll be able to just make merge requests against that branch for merging stable.

Here's what my criteria was:
* typos in documentation or comments
* CI system
* Fixes bugs or potential bugs
* minor enhancements to the distribution mechanisms

Remember, a .z release (x.y.z) is supposed to be bug fixes, if we think we have enough features to make a .y release we can do that instead, but .z releases should not change behavior unless the previous behavior was broken, and optimizations shouldn't go in unless they're vital (if 0.4 took 10 minutes to do some task,and there's a patch that applies cleanly to do it in 1 second, that should go in a .z release), since there is the potential that even minor changes have introduced new regressions. This is important for maintaining trust of distributions, they expect more bugs to be fixed than introduced in a .z release, so we shouldn't push a bunch of refactors and cleanups at them unless they fix bugs.

Does that seem like a reasonable starting place? I can (I think) push that to pazz's repo as 0.4-stable (or whatever color we want to paint our bikeshed) if that seems like a good starting point.

**Comment by dcbaker** [comment] 2017-01-18 00:13
There are a couple of patches I have pending merge to master that I also think might be relevant to a stable release.

**Comment by lucc** [comment] 2017-01-18 00:26
I thought we wanted to branch these 0.4.1 or whatever branches from the current master at some point and then only finish up for the release in them. (With the additional rationale to not block other stuff from going into master).

I agree with your explanation about x.y.z semantics (I understand you to be in line with semver). But I want to point out that we are still pre 1.0 and hence (at least according to semver) can more or less do what we want.

When I understand your proposal correctly you want to open up a new long living stable branch that will only get the bugfix commits on top of 0.4.  Again reminding you about the pre1.0 state I would say it is not the right time to start a separate (long living) branch of development. This point is further strengthened by the fact that we are a very small team and 1) should avoid new big maintenance loads and 2) currently do not seem to have divided interests or areas of work (like one maintainer for 0.4-stable and one for 0.5-dev or so). So I vote for a short living branch 0.4.1 preparing the release instead and if we feel that we have to many new features to carry them around while doing these 0.4.1, 0.4.2, … releases we can always release the new features with an early 0.5 and push the unittest goal to 0.6.

**Comment by dcbaker** [comment] 2017-01-18 18:42
So, since we don't want a long lived release, how about we push the 0.5 milestone to 0.6 and release a 0.5 (there are a few bug fixes that are still baking as merge requests we should probably land first). That way we're not breaking the .z expectation of distributions, but we can get a new release out with new features and the refactors and performance improvements we've landed since then. It's not like theres a limit on the number of .x releases we can do, we could have 0.10 if we need it.

I think it would be better to not do .z releases in pre 1.0 unless we're fixing a serious issue with one or two patches since it sounds like we don't want to have long term maintanence of them.

When we hit 1.0 we should have those kind of longer lived maintenance branches. I would propose that (for example) the 1.0 branch would receive it's last release no later than the time that 1.1 branches, and we make no guarantees of bug fixes for anything except master and the current stable branch. If someone else (like a distro maintainer for a stable distro) wants to take up that maintanence we can discuss that with them.

**Comment by lucc** [comment] 2017-01-18 23:56
I am fine with renaming the current 0.5 milestone to 0.6 and doing a new 0.5 milestone (and release) with the PRs you mentioned. I'm also fine with versions 0.10 and 0.42 ... and I agree with your thoughts about .z releases and what people might expect from them.

I am not yet totally clear on how to manage these stable branches and all that after 1.0 but we have some more time to talk about that.

**Comment by dcbaker** [comment] 2017-01-19 00:05
I think you and I are on the same page, at least on what to do before 1.0, and since 1.0 is going to have python3 support we're probably a ways off from that.

@pazz: How do you feel about renaming the 0.5 milestone to 0.6 and preparing to make a 0.5 release soonish?

**Comment by pazz** [comment] 2017-01-19 09:49
I'm really not that religious about version numbers :) If you two agree its a good idea, then we'll bump .5 to .6 and release .5 soon. I'll rename the milestone now and create an empty .5 milestone. You can then dump your issues in there.

**Comment by lucc** [comment] 2017-01-20 23:16
@dcbaker can you put the stuff you mentioned into the new 0.5 milestone so we know what you think we should concentrate on.

**Comment by dcbaker** [comment] 2017-01-20 23:21
Okay. most of it's landed. Theres on pull request that's basically ready to land (#967), and one that @pazz and I should figure out whether the patch is acceptable or if I should do some work to change it (#966). I think that's about it at this point. Unless you want to fix any of the other bug tags.

**Comment by pazz** [comment] 2017-08-18 08:17
I believe that this issue can be closed?

**Closed** 2017-08-18 15:08 UTC
Labels: deployment
