### ISSUE TITLE
missing quotes for auto-completed contact

### ISSUE THREAD

**Issue by klement** [pazz/alot#990] opened 2017-01-20 12:11 UTC
Hi,
I'm using the notmuch address approach for getting contacts completion with the regexp per docs:
```
regexp = (\"?(?P<name>.+)\"?)?\s*<(?P<email>.*@.+?)>
```
but when I auto-complete the address, instead of getting `"name" <address>` it completes as `name" <address>` so the header looks like this:
```
To: name" <address>
```
instead of:
```
To: "name" <address>
```

**Comment by lucc** [comment] 2017-01-20 12:34
The behavior you see is consistent with the regex. The first quote will not be caught into the group `<name>`. The second quote will always end up in that group as it is matched by `.*` (remember `*` catches as much as it can) and the second `\"?` is never matched as it is optional. If the quotes were not optional the `.*` would be forced not to match it but then the whole thing would only match if there are quotes around the realname, and the whole idea behind the double groups and optional quotes is to match email addresses with and without realnames and the former in turn with and without quotes.

So the conclusion is that the regex given in the docs is buggy. We should try to fix it but that might be very hard, because matching the realname part of an email address with regex is hard (it might for example contain backslash escaped quotes and so on).

PS: I formatted your post for you. Please use [markdown](https://guides.github.com/features/mastering-markdown/) to format your posts yourself in the future.  They are much easier to read if you do.

**Comment by klement** [comment] 2017-01-20 12:42
hmm, maybe the whole regexp could be designed as:

> "a"<b>|<b>

with quotes being mandatory in the first alternative...

**Comment by lucc** [comment] 2017-01-20 12:58
This might be to restrictive (at least for my database, but I use another command altogether so it might still work for you). If I search my database like this: `notmuch address '*'` I get
* emails without a real name, they have no `<` and `>` around them
* emails with a real name, without quotes around the real name
* emails with either single or double quotes around the realname
* emails with single or double quotes around the realname and the other type of quotes in the realname
* surprisingly no quotes of the same type inside a quoted realname, even though I believe I have seen this before, somewhere.
* all emails that have a realname part have at least one space after the realname

**Comment by klement** [comment] 2017-01-20 13:29
while I don't see the describe behaviour, it seems the real problem here is the lack of structur

`notmuch address --format=json` seems to be the answer

the output looks like this:

`{"name": "", "address": "<email>", "name-addr": "<email>"}`
 for emails only

`{"name": "<name>", "address": "<email>", "name-addr": "\"<name>\" <email>"}`

for addresses containing both name and address...

I tried using:

`regexp = {\"name\": \"(?P<name>.+)\", \"address\": \"(?P<email>.+)\", \"name-addr\": \".*\"}[,\]]?`

but am getting:

`...  failed validation: the value "[u'{\\"name\\": \\"(?P<name>.+)\\"', u'\\"address\\": \\"(?P<email>.+)\\"', u'\\"name-addr\\": \\".*\\"}[', u'\\]]?']" is of the wrong type.`

without explanation why

**Comment by lucc** [comment] 2017-01-20 16:21
The problem is that you specified a list as option value instead of a string (see the docs for configobj). Just put single quotes around the whole value and you are fine. You might also consider allowing an optional opening square bracket at the start as the first line from notmuch address will have it.

**Comment by lucc** [comment] 2017-01-20 16:28
Also as you did not make the `name` part optional you only get entries that have a non empty name. If I would use this command I would set the regex like this
```
regexp = '\[?{"name": "(?P<name>.*)", "address": "(?P<email>.+)", "name-addr": ".*"}[,\]]?'
```

**Comment by klement** [comment] 2017-01-20 16:36
the original setting confused me - it might be some kind of special case in the mentioned configobj:

`regexp = (\"?(?P<name>.+)\"?)?\s*<(?P<email>.*@.+?)>`

your final version of regexp matching the json output works fine on my end

I suggest to replace the broken original regexp in the docs with this one

**Comment by lucc** [comment] 2017-01-20 16:40
I already prepared a commit :)

Configobj will guess the type of an option if it is not clearly given. Numbers are numbers (obviously), quoted stuff are strings, things like `True` are boolean and stuff with comma will be used as list whereas any other stuff will be used as string.

Good catch to find the `--format=json` by the way. That makes parsing much easier because there are predictable "markers" before and after the stuff we want to extract.

**Comment by pazz** [comment] 2017-01-20 22:11
Nice one, parsing the json output!
one thing, and this is rather a `notmuch address` bug I think:
I have one recipient of the form `"lastname, firstname" <x@y.com>`.  And notmuch address outputs

```
{"name": "lastname, firstname", "address": "x@y.com", "name-addr": "\"lastname, firstname\" <x@y.com>"}
```

Notice the missing quotes in the name part. They should be there, because otherwise the comma will signal the end of the recipient, when using this string as value for the `To` header.
Should we report this?

**Comment by klement** [comment] 2017-01-20 22:24
This could be fixed by including the quotes in the <name> match...

**Comment by lucc** [comment] 2017-01-20 22:51
I suspect that they will not accept the bug report and instead tell you that the name field holds the plain name. They also have the name-addr field which seems suitable for a To header. It might be our special problem that we want to extract the name and address separately and still use it in a To header. 

Maybe we should check that the name does not mess up our To header in general?

**Comment by pazz** [comment] 2017-01-20 23:20
Quoting Lucas Hoffmann (2017-01-20 22:51:35)
>    I suspect that they will not accept the bug report and instead tell you
>    that the name field holds the plain name. They also have the name-addr
>    field which seems suitable for a To header. It might be our special
>    problem that we want to extract the name and address separately and still
>    use it in a To header.

fair.
 
>    Maybe we should check that the name does not mess up our To header in
>    general?

yes, I think this should go here:
https://github.com/pazz/alot/blob/master/alot/completion.py#L233
I thought about just quoting the realname bit,
so using `\"%s\" <%s>` here. But actually, what happens if the name
contains an odd number of quotes itself?

**Comment by lucc** [comment] 2017-01-24 08:54
Do we still need this issue? (The docs seem fixed and the further discussion can go on in #993)

**Comment by pazz** [comment] 2017-01-24 09:24
OK, closing this here, let's continue in #993 regarding the other problem i mentioned.

**Closed by pazz** 2017-01-24 09:24 UTC
