### ISSUE TITLE
New release/document release policy

### ISSUE THREAD

**Issue by zenhack** [pazz/alot#1189] opened 2018-01-09 20:19 UTC
#1140 has been fixed on master for some time, but still hasn't hit a release. I'm currently running 0.5.1 since that issue is a deal breaker for me, it would be nice if we could tag a release.

More broadly, it would be nice to have a documented release policy/schedule, so in this kind of situation folks aren't twiddling their thumbs wondering when a release is going to happen.

**Comment by pazz** [comment] 2018-01-10 09:41
I have no opinion on a release document. It sounds a bit overkill to me personally but I would not oppose its addition.

Apart from this, I believe that we should make a release soon in order to flush out one last python2 only version and start merging in py3k stuff (which will initially introduce regressions i expect). So, next up is version 1.0?

**Comment by zenhack** [comment] 2018-01-10 12:54
Quoting Patrick Totzke (2018-01-10 04:41:38)

>    I have no opinion on a release document. It sounds a bit overkill to me
>    personally but I would not oppose its addition.

"release document" does sound like overkill; I just meant something
simple; for [simp_le][1] we just have one sentence in the readme:

```
Releases occur approximately every two months, unless there is a
pressing need to do otherwise (e.g. security & serious bug fixes).
```

That's more the kind of thing I had in mind.

[1]: https://github.com/zenhack/simp_le

**Comment by pazz** [comment] 2018-01-10 14:06
@lucc @dcbaker: how's your stand here? I'm OK with such a comment in the
README but would not want to press on with a release unless we actually
have non-trivial changes.

But loosely promising a point release every 6 months sounds OK to me.

**Comment by lucc** [comment] 2018-01-10 14:21
*I* don't like to commit myself to releasing stuff in regular time intervals. But *we* can still do that :) So you can put something in the README if that is necessary.

I don't understand how "1.0" suggests itself as the next version? I admit that I think in terms like semantic versioning. And then I would wait for py3 to be merged and regressions to be fixed before going for 1.0 (note that version numbers are not decimal numbers so after 0.9 there is 0.10 and not necessarily 1.0)

On the other hand: Yes, let's release 0.8 or 0.7.x or whatever.

**Comment by pazz** [comment] 2018-01-10 14:25
Quoting Lucas Hoffmann (2018-01-10 14:21:13)
> I don't like to commit myself to releasing stuff in regular time intervals. But
> we can still do that :) So you can put something in the README if that is
> necessary.

OK I'm with you.

> I don't understand how "1.0" suggests itself as the next version? I admit that
> I think in terms like semantic versioning. And then I would wait for py3 to be
> merged and regressions to be fixed before going for 1.0 (note that version
> numbers are not decimal numbers so after 0.9 there is 0.10 and not necessarily
> 1.0)

The thinking was that switching to less reliable python3 stuff is a big
thing and a mayor release would reflect that.
But we can similarly delay the major bump until we have something to
show for in terms of moving to py3.
I'm fine with a v0.8 release tag.

**Comment by lucc** [comment] 2018-01-10 14:29
To say that the last version with py2 is 1.0 and the first with py3 is 2.0 also makes sense. The bug fixes for py3 go into 2.1 or 2.0.1 ... then.

**Comment by pazz** [comment] 2018-01-10 17:32
I'm fine either way. Let's delegate this difficult decision to our third man :)

**Comment by pazz** [comment] 2018-01-28 12:53
I've tagged a new release candidate. 0.7rc1.
@lucc, @dcbaker If you have anything you want to get in let us know. If nothing happens in a week, Ill just trigger the process then.

**Comment by pazz** [comment] 2018-06-19 08:59
0.7 was release a while back, so I'll close this issue.
I've refrained from adding a promise of regular releases to the README because I believe that that info can be extracted better by looking at the github activity.

**Closed by pazz** 2018-06-19 08:59 UTC
