### ISSUE TITLE
questions and troube with ce31ecf.

### ISSUE THREAD

**Issue by lucc** [pazz/alot#812] opened 2015-12-18 02:25 UTC
If I understand ce31ecf correctly it is intended to make alot usable with the python -m switch and such. I get mixed results:
```sh
cd ~/vcs/alot
python2 setup.py build
cd build/lib
python2 alot/__main__.py # works
python2 alot             # works
python2 -m alot          # fails
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/luc/vcs/alot/build/lib/alot/__main__.py", line 12, in <module>
    from alot.ui import UI
  File "alot/ui.py", line 9, in <module>
    from buffers import BufferlistBuffer
  File "alot/buffers.py", line 20, in <module>
    from alot.widgets.thread import ThreadTree
  File "alot/widgets/thread.py", line 15, in <module>
    from urwidtrees import Tree, SimpleTree, CollapsibleTree
ImportError: No module named urwidtrees
```

But inside `__main__,py` the `if __name__ == '__main__':` check should not be needed. See https://docs.python.org/2/using/cmdline.html#interface-options (description of `<script>`).

**Comment by pazz** [comment] 2015-12-18 06:47
Quoting Lucas Hoffmann (2015-12-18 02:25:44)
>    If I understand [1]ce31ecf correctly it is intended to make alot usable
>    with the python -m switch and such I get mixed results:
> 
>  cd ~/vcs/alot
>  python2 setuppy build
>  cd build/lib
>  python2 alot/__main__py # works
>  python2 alot             # works
>  python2 -m alot          # fails
>  Traceback (most recent call last):
>    File "/usr/lib/python27/runpypy", line 162, in _run_module_as_main
>      "__main__", fname, loader, pkg_name)
>    File "/usr/lib/python27/runpypy", line 72, in _run_code
>      exec code in run_globals
>    File "/home/luc/vcs/alot/build/lib/alot/__main__py", line 12, in <module>
>      from alotui import UI
>    File "alot/uipy", line 9, in <module>
>      from buffers import BufferlistBuffer
>    File "alot/bufferspy", line 20, in <module>
>      from alotwidgetsthread import ThreadTree
>    File "alot/widgets/threadpy", line 15, in <module>
>      from urwidtrees import Tree, SimpleTree, CollapsibleTree
>  ImportError: No module named urwidtrees

And you are sure you have urwidtrees installed?
Did you run alot from git master before?
because this is a new (in comparison to v0.3.6) dependency.
 
>    But inside __main__,py the if __name__ == '__main__': check should not be
>    needed See https://docspythonorg/2/using/cmdlinehtml#interface-options
>    (description of <script>)


Thanks for this, I will amend it.

**Comment by lucc** [comment] 2015-12-18 11:35
Yes I had and have urwidtrees installed and I was running master before.

I'm sorry I can not pinpoint the problem at the moment. First the trouble where as described above. In the mean time I experienced trouble with my `abook` section. I get a message that alot `Could not read /home/luc/.config/abook/addressbook` at startup and alot terminates. The relevant part of the config looks like this:
```
[accounts]
[[web]]
# ...
[[[abook]]]
type = abook
abook_contacts_file = ~/.config/abook/addressbook
```
If I uncomment my abook section all three invocations of alot work as expected.

So I have to debug my addressbook first. Sorry for the noise.

**Comment by pazz** [comment] 2015-12-18 15:56
your config snippet looks ok to me.
I will close this issue for now but don;t hesitate to reopen in case you can (make others) reproduce the original problem.

**Closed by pazz** 2015-12-18 15:56 UTC
