### ISSUE TITLE
encoding troubles in error message

### ISSUE THREAD

**Issue by teythoon** [pazz/alot#824] opened 2016-01-04 10:34 UTC
I have a problem with the address completer.  I enter some prefix, hit tab, then alot freezes, and when I press ctrl-c, I get:

```
Traceback (most recent call last):
  File "/home/teythoon/.local/bin/alot", line 9, in <module>
    load_entry_point('alot==0.3.7.dev1', 'console_scripts', 'alot')()
  File "/home/teythoon/.local/stow/alot/lib/python2.7/site-packages/alot-0.3.7.dev1-py2.7.egg/alot/init.py", line 186, in main
    UI(dbman, cmdstring)
  File "/home/teythoon/.local/stow/alot/lib/python2.7/site-packages/alot-0.3.7.dev1-py2.7.egg/alot/ui.py", line 87, in __init__
    self.mainloop.run()
  File "/usr/lib/python2.7/dist-packages/urwid/main_loop.py", line 274, in run
    self.screen.run_wrapper(self._run)
  File "/usr/lib/python2.7/dist-packages/urwid/raw_display.py", line 268, in run_wrapper
    return fn()
  File "/usr/lib/python2.7/dist-packages/urwid/main_loop.py", line 339, in _run
    self.event_loop.run()
  File "/usr/lib/python2.7/dist-packages/urwid/main_loop.py", line 1183, in wrapper
    rval = f(*args,**kargs)
  File "/usr/lib/python2.7/dist-packages/urwid/main_loop.py", line 390, in _update
    self.process_input(keys)
  File "/usr/lib/python2.7/dist-packages/urwid/main_loop.py", line 490, in process_input
    k = self._topmost_widget.keypress(self.screen_size, k)
  File "/usr/lib/python2.7/dist-packages/urwid/container.py", line 588, in keypress
    *self.calculate_padding_filler(size, True)), key)
  File "/usr/lib/python2.7/dist-packages/urwid/container.py", line 2265, in keypress
    key = w.keypress((mc,) + size[1:], key)
  File "/home/teythoon/.local/stow/alot/lib/python2.7/site-packages/alot-0.3.7.dev1-py2.7.egg/alot/widgets/globals.py", line 145, in keypress
    self.on_error(e)
  File "/home/teythoon/.local/stow/alot/lib/python2.7/site-packages/alot-0.3.7.dev1-py2.7.egg/alot/ui.py", line 276, in cerror
    self.notify('completion error: %s' % e.message,
UnicodeEncodeError: 'ascii' codec can't encode character u'\u015b' in position 1155: ordinal not in range(128)
```

**Comment by lucc** [comment] 2017-08-09 09:16
This bug still exists. To reproduce you can type some non ascii char in the `To` prompt when composing a new message. I assume it has to be a char that doesn't have a match in your address book. So I used `ĸ`.

**Comment by three-comrades** [comment] 2018-01-08 17:57
Hm, I can't reproduce this on master or alot 0.6/0.5.1. 

What is the original error `e` that causes the encoding error here, when alot tries to report it?

**Comment by lucc** [comment] 2018-01-08 23:19
I can still reproduce this on master (0.6-112-g4a67ce79). I issue `:compose` then press ENTER to select the sending address and the paste the `ĸ` and then hit TAB. This immediately crashes alot with a stacktrace printed to screen. The process freezes and can not be killed with ctrl-c. I have to kill-9 it.
Currently the stacktrace (maybe with newer line numbers compared to 2016) is this:
```
Traceback (most recent call last):
  File "/home/luc/.local/bin/alot", line 11, in <module>
    load_entry_point('alot', 'console_scripts', 'alot')()
  File "/home/luc/vcs/alot/alot/__main__.py", line 132, in main
    UI(dbman, cmdstring)
  File "/home/luc/vcs/alot/alot/ui.py", line 124, in __init__
    self.mainloop.run()
  File "/home/luc/.local/lib/python2.7/site-packages/urwid/main_loop.py", line 278, in run
    self._run()
  File "/home/luc/.local/lib/python2.7/site-packages/urwid/main_loop.py", line 376, in _run
    self.event_loop.run()
  File "/home/luc/.local/lib/python2.7/site-packages/urwid/main_loop.py", line 1200, in wrapper
    rval = f(*args,**kargs)
  File "/home/luc/.local/lib/python2.7/site-packages/urwid/raw_display.py", line 393, in <lambda>
    event_loop, callback, self.get_available_raw_input())
  File "/home/luc/.local/lib/python2.7/site-packages/urwid/raw_display.py", line 493, in parse_input
    callback(processed, processed_codes)
  File "/home/luc/.local/lib/python2.7/site-packages/urwid/main_loop.py", line 403, in _update
    self.process_input(keys)
  File "/home/luc/.local/lib/python2.7/site-packages/urwid/main_loop.py", line 503, in process_input
    k = self._topmost_widget.keypress(self.screen_size, k)
  File "/home/luc/.local/lib/python2.7/site-packages/urwid/container.py", line 592, in keypress
    *self.calculate_padding_filler(size, True)), key)
  File "/home/luc/.local/lib/python2.7/site-packages/urwid/container.py", line 2269, in keypress
    key = w.keypress((mc,) + size[1:], key)
  File "/home/luc/vcs/alot/alot/widgets/globals.py", line 148, in keypress
    self.on_error(e)
  File "/home/luc/vcs/alot/alot/ui.py", line 314, in cerror
    self.notify('completion error: %s' % e.message,
UnicodeEncodeError: 'ascii' codec can't encode character u'\u0138' in position 41: ordinal not in range(128)
```
The log file is of no help as it ends with these lines:
```
DEBUG:ui:cmdline: 'compose'
DEBUG:ui:bufferlist command string: "compose"
DEBUG:__init__:mode:bufferlist got commandline "compose"
DEBUG:__init__:ARGS: [u'compose']
DEBUG:__init__:cmd parms {'spawn': None, 'sender': None, 'attach': None, 'cc': None, 'omit_signature': False, 'rest': [], 'bcc': None, 'to': None, 'template': None, 'subject': None}
DEBUG:envelope:TEMPLATE: None
DEBUG:ui:Got key (['enter'], [10])
DEBUG:globals:True
DEBUG:globals:[<alot.addressbook.external.ExternalAddressbook object at 0x7f3b33470590>]
DEBUG:ui:Got key ([u'\u0138'], [196, 184])
DEBUG:ui:Got key (['tab'], [9])
```

**Comment by three-comrades** [comment] 2018-01-10 03:00
Two thoughts:
- this may fix itself with python 3
- other than that, the only difference I can see is that you seem to use `type = shellcommand` for your addressbook, whereas I use `type = abook`. What is your `[abook]` section in the config?

**Comment by three-comrades** [comment] 2018-01-23 23:19
I think I can reproduce this:
- configure an external abook command that throws an error. For example a script like this:
```
#! /bin/sh
exit 1
```
- follow @lucc's steps: `alot compose`, <enter,> ĸ, <tab> results in the reported stack trace.

My branch [here](https://github.com/three-comrades/alot/commits/fix_crash_on_unicode) fixes it for me.

**Comment by pazz** [comment] 2018-01-28 12:16
my 2¢: all works as expected here. 

```
DEBUG:__init__:ARGS: [u'compose']
DEBUG:__init__:cmd parms {'spawn': None, 'sender': None, 'attach': None, 'cc': None, 'omit_signature': False, 'rest': [], 'bcc': None, 'to': None, 'template': None, 'subject': None}
DEBUG:envelope:TEMPLATE: None
DEBUG:ui:Got key (['enter'], [10])
DEBUG:globals:True
DEBUG:globals:[<alot.addressbook.external.ExternalAddressbook object at 0x7f908fdb5f50>]
DEBUG:ui:Got key (['k'], [107])
DEBUG:ui:Got key (['tab'], [9])
ERROR:ui:abook command "bin/failab" returned with return code 1

```

**Comment by three-comrades** [comment] 2018-01-28 12:21
> DEBUG:ui:Got key (['k'], [107])

Note that we used  `ĸ` here, not a latin k :-)

> DEBUG:ui:Got key ([u'\u0138'], [196, 184])

**Comment by pazz** [comment] 2018-01-28 12:27
oh! thanks. Anyways: same same
```
DEBUG:ui:Got key ([u'\u0138'], [196, 184])
DEBUG:ui:Got key (['tab'], [9])
ERROR:ui:abook command "bin/failab" returned with return code 1
```

**Comment by three-comrades** [comment] 2018-02-15 23:22
I think you don't get the crash, because for some reason the key is not passed to `bin/failab` and thus it's not part of the error message. When I use an ascii-key (here `u`)  with the fake abook, I get the following log message, i.e. the key is part of the command string :
```
ERROR:ui:abook command "/home/kelvin/bin/foo.sh u" returned with return code 1
```

- My abook-shellcommand definition for the sender account I use, where `foo.sh` is the `exit 1` shell script:
```
        [[[abook]]]
            type=shellcommand
            command = /home/kelvin/bin/foo.sh
            regexp = \"(?P<name>.+)\"\s*<(?P<email>.*.+?@.+?)>
```
- `alot -l log -d debug compose --sender julian.mehne@posteo.de`, `ö`, `<tab>`, crash when trying to print the error message from the failed sene command.
- full log:
```
DEBUG:manager:template directory: `/home/kelvin/.config/alot/templates`
DEBUG:manager:themes directory: `/home/kelvin/.config/alot/themes`
DEBUG:manager:abook defined: {u'type': u'shellcommand', u'command': u'/home/kelvin/bin/foo.sh', u'regexp': u'\\"(?P<name>.+)\\"\\s*<(?P<email>.*.+?@.+?)>', 'ignorecase': True, 'abook_contacts_file': '/home/kelvin/.abook/addressbook', 'shellcommand_external_filtering': True}
INFO:ui:setup gui in 256 colours
DEBUG:ui:fire first command
DEBUG:ui:global command string: "compose --sender julian.mehne@posteo.de"
DEBUG:__init__:mode:global got commandline "compose --sender julian.mehne@posteo.de"
DEBUG:__init__:ARGS: [u'compose', u'--sender', u'julian.mehne@posteo.de']
DEBUG:__init__:cmd parms {'spawn': None, 'sender': u'julian.mehne@posteo.de', 'tags': None, 'cc': None, 'omit_signature': False, 'rest': [], 'bcc': None, 'to': None, 'template': None, 'attach': None, 'subject': None}
DEBUG:envelope:TEMPLATE: None
DEBUG:globals:True
DEBUG:globals:[<alot.addressbook.external.ExternalAddressbook object at 0x7ffb80613190>]
DEBUG:ui:Got key ([u'\xf6'], [195, 182])
DEBUG:ui:Got key (['tab'], [9])
```

**Comment by varac** [comment] 2018-07-06 19:45
I can reproduce this with alot@44abb20d, built with python 3.
I use `notmuch-addrlookup` `0.9` to auto complete contacts.

```
[[[abook]]]
    type = shellcommand                                                                                                                                                              
    command = /usr/bin/notmuch-addrlookup                                                                                                                                            
    regexp = ^((?P<name>[^(\\s+\<)]*)\s+<)?(?P<email>[^@]+?@[^>]+)>?$       
```

Whenever I get results that contain a non-ascii character in contact names (i.e. "Ólafur"), I get this crash:

```
Traceback (most recent call last):
  File "/home/varac/.local/bin/alot", line 11, in <module>
    load_entry_point('alot==0.7', 'console_scripts', 'alot')()
  File "/home/varac/.local/lib/python3.6/site-packages/alot-0.7-py3.6.egg/alot/__main__.py", line 128, in main
    UI(dbman, cmdstring)
  File "/home/varac/.local/lib/python3.6/site-packages/alot-0.7-py3.6.egg/alot/ui.py", line 130, in __init__
    self.mainloop.run()
  File "/home/varac/.local/lib/python3.6/site-packages/urwid/main_loop.py", line 286, in run
    self._run()
  File "/home/varac/.local/lib/python3.6/site-packages/urwid/main_loop.py", line 384, in _run
    self.event_loop.run()
  File "/home/varac/.local/lib/python3.6/site-packages/urwid/main_loop.py", line 1340, in run
    reraise(*exc_info)
  File "/home/varac/.local/lib/python3.6/site-packages/urwid/compat.py", line 58, in reraise
    raise value
  File "/home/varac/.local/lib/python3.6/site-packages/urwid/main_loop.py", line 1354, in wrapper
    rval = f(*args,**kargs)
  File "/home/varac/.local/lib/python3.6/site-packages/urwid/raw_display.py", line 404, in <lambda>
    event_loop, callback, self.get_available_raw_input())
  File "/home/varac/.local/lib/python3.6/site-packages/urwid/raw_display.py", line 502, in parse_input
    callback(processed, processed_codes)
  File "/home/varac/.local/lib/python3.6/site-packages/urwid/main_loop.py", line 411, in _update
    self.process_input(keys)
  File "/home/varac/.local/lib/python3.6/site-packages/urwid/main_loop.py", line 511, in process_input
    k = self._topmost_widget.keypress(self.screen_size, k)
  File "/home/varac/.local/lib/python3.6/site-packages/urwid/container.py", line 595, in keypress
    *self.calculate_padding_filler(size, True)), key)
  File "/home/varac/.local/lib/python3.6/site-packages/urwid/container.py", line 2271, in keypress
    key = w.keypress((mc,) + size[1:], key)
  File "/home/varac/.local/lib/python3.6/site-packages/alot-0.7-py3.6.egg/alot/widgets/globals.py", line 145, in keypress
    self.edit_pos)
  File "/home/varac/.local/lib/python3.6/site-packages/alot-0.7-py3.6.egg/alot/completion.py", line 118, in complete
    for c, _ in self._completer.complete(mypart, mypos):
  File "/home/varac/.local/lib/python3.6/site-packages/alot-0.7-py3.6.egg/alot/completion.py", line 234, in complete
    newtext = email.utils.formataddr((name, addr))
  File "/usr/lib/python3.6/email/utils.py", line 91, in formataddr
    address.encode('ascii')
UnicodeEncodeError: 'ascii' codec can't encode character '\xb7' in position 1: ordinal not in range(128)
```

**Comment by varac** [comment] 2018-07-06 19:46
It's kind of annoying because everytime I get the above traceback I need to restart alot.

**Comment by varac** [comment] 2018-07-06 19:57
I work around the issue by using a wrapper script now for addr completion which converts all UTF8 chars to ascii:

```
#!/bin/sh
ARGS="$*"
notmuch-addrlookup "$ARGS" | konwert utf8-ascii
```

It's not perfect but works around the bug. Please fix it properly though.

**Comment by dcbaker** [comment] 2018-08-01 19:11
I believe this issue has been resolved in python3, since formataddr now assumes it's being passed utf-8 enocded strings instead of ascii strings.

**Comment by lucc** [comment] 2018-08-01 21:06
I think so to I can not reproduce the issue any longer.

**Closed by lucc** 2018-08-01 21:06 UTC
Labels: bug
