### ISSUE TITLE
'bclose;refresh' freeze alot

### ISSUE THREAD

**Issue by cinghiopinghio** [pazz/alot#749] opened 2015-01-14 09:40 UTC
Hello @pazz,
I'm not really sure this is a bug.
I was trying to get the search buffer refreshed after I'm done with some reading/replying/writing and some emails have been downloaded and indexed in the meantime.

I thought that forcing a `refresh` after closing a buffer whould suffice so I have the following configuration (only relevant parts):
```
quit_on_last_bclose = True
[bindings]
   q=bclose;refresh
```
Which works most of the times but it causes alot to freeze without any debug logs of any kind if the buffer is the last one (and I expect alot to exit without refresh).

**Comment by pazz** [comment] 2015-05-15 11:15
sorry for my late reply. Actually i cannot reproduce this at all with current testing or master branches.
Can anyone confirm this bug? otherwise i'll close the issue..

**Comment by cinghiopinghio** [comment] 2015-05-15 12:18
Hi pazz,
I almost forgot this bug (and since then changed the bindings), but with the latest build I cannot reproduce this anymore.

One small question: Is there a way to keep the same line highlighted after a refresh?

**Comment by pazz** [comment] 2015-05-15 12:30
OK great, i'll close the issue then.
Regarding you question: as far as i'm aware there is no easy way to do this, since a refresh would rebuild all widgets in the buffer and focus positions are properties of (container) widgets.
This should however be doable (read hacky solution that should really be done by the API):
The focus positions in MessageTrees are message-id header values iirc. So one could

* get the focussed message
* extract its Message-ID header value = focus position identifier
* rebuild the ThreadBuffer (builds new Tree widgets)
* tell the new tree to focus the message with the saved ID

This assumes of course that the previously focussed message is still indexed and still matches the search query, which is usually true but not at all guaranteed..

**Closed by pazz** 2015-05-15 12:30 UTC
