### ISSUE TITLE
CTRL+C during prompt causes alot to freeze

### ISSUE THREAD

**Issue by pwnage101** [pazz/alot#888] opened 2016-07-23 15:46 UTC
Esc cancels open prompts, but sometimes I press CTRL+C instead.  I know this is wrong, but regardless it should not cause alot to become frozen.  I suppose it should just quit alot, which is the most consistent behavior.

steps to reproduce:
1. press m
2. press CTRL+C

alot git commit: 747b894bbe2156bae2c1f128ec0b4344d7c28378

**Comment by pazz** [comment] 2016-07-24 08:50
I cannot reproduce this, for me it behaves as expected and exits alot.
Can you try with an up to date master branch?

**Comment by pwnage101** [comment] 2016-07-24 19:05
The git commit I referenced was the head of master at the time.  I'll investigate more later.

**Comment by pazz** [comment] 2016-12-18 23:43
I'll close this here, you're welcome to re-open the issue if you find out how to reproduce this exactly. Thanks

**Closed by pazz** 2016-12-18 23:43 UTC
